language: node_js
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
env:
  - CXX="g++-4.8"
before_script:
  - npm run build-server
node_js:
  - "7"
  - "6"
